class CustomerIntents:

    SEARCH_PRODUCTS = "SEARCH_PRODUCTS"

    MY_ORDERS = "MY_ORDERS"

    LATEST_ORDER = "LATEST_ORDER"

    ORDERS_BY_STATUS = "ORDERS_BY_STATUS"

    ORDERS_BETWEEN_DATES = "ORDERS_BETWEEN_DATES"

    PURCHASED_PRODUCTS = "PURCHASED_PRODUCTS"

    HAS_PURCHASED_PRODUCT = "HAS_PURCHASED_PRODUCT"

    RECENTLY_VIEWED_PRODUCTS = "RECENTLY_VIEWED_PRODUCTS"

    LAST_VIEWED_PRODUCT = "LAST_VIEWED_PRODUCT"
