# Generated by Django 5.2.4 on 2026-06-10 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
    ]
