# Generated by Django 5.2.4 on 2026-06-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_productview"),
    ]

    operations = [
        migrations.AddField(
            model_name="productview",
            name="view_count",
            field=models.IntegerField(default=1),
        ),
    ]
