# Generated by Django 5.2.4 on 2026-06-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_productview_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("customer", "Customer")],
                default="customer",
                max_length=20,
            ),
        ),
    ]
