# Generated by Django 5.2.4 on 2026-07-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_devicetoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="desc",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(max_length=120),
        ),
    ]
