# Generated by Django 5.2.4 on 2026-08-19 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_contactmessage_alter_notification_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicetoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="device_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
